sudo: false
language: python
matrix:
    include:
        - python: 3.8
          env: TOXENV=flake8
        - python: 3.8
          env: TOXENV=pylint
        - python: 3.8
          env: TOXENV=mypy
        - python: 3.6
          env: TOXENV=py36-django22
        - python: 3.6
          env: TOXENV=py36-django30
        - python: 3.6
          env: TOXENV=py36-django31
        - python: 3.7
          env: TOXENV=py37-django22
          dist: xenial
        - python: 3.7
          env: TOXENV=py37-django30
          dist: xenial
        - python: 3.7
          env: TOXENV=py37-django31
          dist: xenial
        - python: 3.8
          env: TOXENV=py38-django22
          dist: xenial
        - python: 3.8
          env: TOXENV=py38-django30
          dist: xenial
        - python: 3.8
          env: TOXENV=py38-django31
          dist: xenial
services:
    - postgresql
addons:
    postgresql: "10"
before_script:
    - psql -c 'CREATE DATABASE small_small_hr;' -U postgres
install:
    - pip install tox
script: tox
